ci: add docker build
naviteq/curator-opensearch pull request #6
Opened 2022-12-07 08:59 UTC by KFearsoff

2022-12-12 09:47 UTC, DovnarAlexander requested changes

2022-12-12 09:47 UTC, DovnarAlexander commented on .github/workflows/schedule.yaml
Let's add cron expression

2022-12-12 10:39 UTC, KFearsoff commented on .github/workflows/schedule.yaml
I think there's already one at line 3

2022-12-13 12:23 UTC, DovnarAlexander approved these changes

2022-12-13 12:23 UTC, merged